const ShopActionsTypes = {
  FETCH_COLLECTIONS_START_ASYNC: "FETCH_COLLECTIONS_START_ASYNC",
  FETCH_COLLECTIONS_SUCCES: "FETCH_COLLECTIONS_SUCCES",
  FECTH_COLLECTIONS_FAILURE: "FECTH_COLLECTIONS_FAILURE",
};

export default ShopActionsTypes;
